name: Infraestrutura Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Terraform 
      - name: Inicializando Terraform
        run: program/terraform.exe init        
      - name: Criando plano
        run: program/terraform.exe plan --out infra.tfplan -var="aws_access_key=${{ secrets.TF_VAR_AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.TF_VAR_AWS_SECRET_KEY }}"
      - name: Executando plano
        run: program/terraform.exe apply infra.tfplan 
